export const roles = {
  superadmin: {
    name: "SuperAdmin",
    capabilities: [
      "create_sites",
      "delete_sites",
      "manage_network",
      "manage_sites",
      "manage_network_users",
      "manage_network_plugins",
      "manage_network_themes",
      "manage_network_options",
      "upgrade_network",
      "setup_network",
      "switch_themes",
      "edit_themes",
      "activate_plugins",
      "edit_plugins",
      "edit_users",
      "edit_files",
      "manage_options",
      "moderate_comments",
      "manage_categories",
      "manage_links",
      "upload_files",
      "import",
      "unfiltered_html",
      "edit_posts",
      "edit_others_posts",
      "edit_published_posts",
      "publish_posts",
      "edit_pages",
      "read",
      "level_10",
      "level_9",
      "level_8",
      "level_7",
      "level_6",
      "level_5",
      "level_4",
      "level_3",
      "level_2",
      "level_1",
      "level_0",
      "edit_others_pages",
      "edit_published_pages",
      "publish_pages",
      "delete_pages",
      "delete_others_pages",
      "delete_published_pages",
      "delete_posts",
      "delete_others_posts",
      "delete_published_posts",
      "delete_private_posts",
      "edit_private_posts",
      "read_private_posts",
      "delete_private_pages",
      "edit_private_pages",
      "read_private_pages",
      "delete_users",
      "create_users",
      "unfiltered_upload",
      "edit_dashboard",
      "update_plugins",
      "delete_plugins",
      "install_plugins",
      "update_themes",
      "install_themes",
      "update_core",
      "list_users",
      "remove_users",
      "promote_users",
      "edit_theme_options",
      "delete_themes",
      "export",
    ],
  },
  administrator: {
    name: "Administrator",
    capabilities: [
      "switch_themes",
      "edit_themes",
      "activate_plugins",
      "edit_plugins",
      "edit_users",
      "edit_files",
      "manage_options",
      "moderate_comments",
      "manage_categories",
      "manage_links",
      "upload_files",
      "import",
      "unfiltered_html",
      "edit_posts",
      "edit_others_posts",
      "edit_published_posts",
      "publish_posts",
      "edit_pages",
      "read",
      "level_10",
      "level_9",
      "level_8",
      "level_7",
      "level_6",
      "level_5",
      "level_4",
      "level_3",
      "level_2",
      "level_1",
      "level_0",
      "edit_others_pages",
      "edit_published_pages",
      "publish_pages",
      "delete_pages",
      "delete_others_pages",
      "delete_published_pages",
      "delete_posts",
      "delete_others_posts",
      "delete_published_posts",
      "delete_private_posts",
      "edit_private_posts",
      "read_private_posts",
      "delete_private_pages",
      "edit_private_pages",
      "read_private_pages",
      "delete_users",
      "create_users",
      "unfiltered_upload",
      "edit_dashboard",
      "update_plugins",
      "delete_plugins",
      "install_plugins",
      "update_themes",
      "install_themes",
      "update_core",
      "list_users",
      "remove_users",
      "promote_users",
      "edit_theme_options",
      "delete_themes",
      "export",
    ],
  },
  editor: {
    name: "Editor",
    capabilities: [
      "moderate_comments",
      "manage_categories",
      "manage_links",
      "upload_files",
      "unfiltered_html",
      "edit_posts",
      "edit_others_posts",
      "edit_published_posts",
      "publish_posts",
      "edit_pages",
      "read",
      "level_7",
      "level_6",
      "level_5",
      "level_4",
      "level_3",
      "level_2",
      "level_1",
      "level_0",
      "edit_others_pages",
      "edit_published_pages",
      "publish_pages",
      "delete_pages",
      "delete_others_pages",
      "delete_published_pages",
      "delete_posts",
      "delete_others_posts",
      "delete_published_posts",
      "delete_private_posts",
      "edit_private_posts",
      "read_private_posts",
      "delete_private_pages",
      "edit_private_pages",
      "read_private_pages",
    ],
  },
  author: {
    name: "Author",
    capabilities: [
      "upload_files",
      "edit_posts",
      "edit_published_posts",
      "publish_posts",
      "read",
      "level_2",
      "level_1",
      "level_0",
      "delete_posts",
      "delete_published_posts",
    ],
  },
  contributor: {
    name: "Contributor",
    capabilities: ["edit_posts", "read", "level_1", "level_0", "delete_posts"],
  },
  subscriber: {
    name: "Subscriber",
    capabilities: ["read", "level_0"],
  },
  anonymous: {
    name: "Anonymous",
    capabilities: [],
  },
};
