import { z } from "zod";
import { mySQLDateWithZeroDefaultDate } from "./date";

export const options = z.object({
  siteurl: z.string(),
  home: z.string(),
  blogname: z.string(),
  blogdescription: z.string(),
  users_can_register: z.number().min(0).max(1),
  admin_email: z.string().email(),
  start_of_week: z.number().min(0).max(1), // You might want to have specific checks if it's always "0" or "1"
  use_balanceTags: z.number().min(0).max(1),
  use_smilies: z.number().min(0).max(1),
  require_name_email: z.number().min(0).max(1),
  comments_notify: z.number().min(0).max(1),
  posts_per_rss: z.number(),
  rss_use_excerpt: z.number().min(0).max(1),
  mailserver_url: z.string(),
  mailserver_login: z.string().email(),
  mailserver_pass: z.string(),
  mailserver_port: z.number(),
  default_category: z.number(),
  default_comment_status: z.string(),
  default_ping_status: z.string(),
  default_pingback_flag: z.number().min(0).max(1),
  posts_per_page: z.number(),
  date_format: z.string(),
  time_format: z.string(),
  links_updated_date_format: z.string(),
  comment_moderation: z.number().min(0).max(1),
  moderation_notify: z.number().min(0).max(1),
  permalink_structure: z.string(),
  rewrite_rules: z.string(),
  hack_file: z.number().min(0).max(1),
  blog_charset: z.string(),
  moderation_keys: z.string(),
  active_plugins: z.array(z.string()),
  category_base: z.string(),
  ping_sites: z.string(),
  comment_max_links: z.number(),
  gmt_offset: z.any(), // You might want to define this more strictly based on how gmtOffset is defined
  default_email_category: z.number(),
  recently_edited: z.string(),
  template: z.any(), // You might want to define this more strictly based on how template is defined
  stylesheet: z.any(), // You might want to define this more strictly based on how stylesheet is defined
  comment_registration: z.number().min(0).max(1),
  html_type: z.string(),
  use_trackback: z.number().min(0).max(1),
  default_role: z.string(),
  db_version: z.any(), // You might want to define this more strictly based on how WPDBversion is defined
  uploads_use_yearmonth_folders: z.number().min(0).max(1),
  upload_path: z.string(),
  blog_public: z.string(),
  default_link_category: z.number(),
  show_on_front: z.string(),
  tag_base: z.string(),
  show_avatars: z.string(),
  avatar_rating: z.string(),
  upload_url_path: z.string(),
  thumbnail_size_w: z.number(),
  thumbnail_size_h: z.number(),
  thumbnail_crop: z.number().min(0).max(1),
  medium_size_w: z.number(),
  medium_size_h: z.number(),
  avatar_default: z.string(),
  large_size_w: z.number(),
  large_size_h: z.number(),
  image_default_link_type: z.string(),
  image_default_size: z.string(),
  image_default_align: z.string(),
  close_comments_for_old_posts: z.number().min(0).max(1),
  close_comments_days_old: z.number(),
  thread_comments: z.number().min(0).max(1),
  thread_comments_depth: z.number(),
  page_comments: z.number().min(0).max(1),
  comments_per_page: z.number(),
  default_comments_page: z.string(),
  comment_order: z.string(),
  sticky_posts: z.array(z.any()), // Define this based on the structure of sticky_posts
  widget_categories: z.array(z.any()), // Define this based on the structure of widget_categories
  widget_text: z.array(z.any()), // Define this based on the structure of widget_text
  widget_rss: z.array(z.any()), // Define this based on the structure of widget_rss
  uninstall_plugins: z.array(z.any()), // Define this based on the structure of uninstall_plugins
  timezone_string: z.any(), // You might want to define this more strictly based on how timezoneString is defined
  page_for_posts: z.number(),
  page_on_front: z.number(),
  default_post_format: z.number(),
  link_manager_enabled: z.number().min(0).max(1),
  finished_splitting_shared_terms: z.number().min(0).max(1),
  site_icon: z.number(),
  medium_large_size_w: z.number(),
  medium_large_size_h: z.number(),
  wp_page_for_privacy_policy: z.number(),
  show_comments_cookies_opt_in: z.number().min(0).max(1),
  admin_email_lifespan: mySQLDateWithZeroDefaultDate,
  disallowed_keys: z.string(),
  comment_previously_approved: z.number().min(0).max(1),
  auto_plugin_theme_update_emails: z.array(z.any()), // Define this based on the structure of auto_plugin_theme_update_emails
  auto_update_core_dev: z.string(),
  auto_update_core_minor: z.string(),
  auto_update_core_major: z.string(),
  wp_force_deactivated_plugins: z.array(z.any()), // Define this based on the structure of wp_force_deactivated_plugins
  wp_attachment_pages_enabled: z.number().min(0).max(1),
});
